Revert "[EAP 8.2 Helm Charts + Java 25] Modify WildflyImageOpenShiftProvisioner to bypass XTF's broken PVC builder: Fix NoSuchMethodError by bypassing XTF PVC builder"
This reverts commit c94eb2b8e7d95da70704d5cfd029ffb118e19c75.